# Generated by Django 3.1.1 on 2020-10-18 13:24

from django.db import migrations, models
import novel_app.models
import novel_app.storages


class Migration(migrations.Migration):

    dependencies = [
        ('novel_app', '0019_auto_20201018_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.FileField(blank=True, null=True, storage=novel_app.storages.ProtectedStorage(), upload_to=novel_app.models.create_chapter_path),
        ),
    ] 
